import * as litematica from '@cartographer/litematica';
import { MCBlockSpace } from '../../block-generation';

/**
 * Converts BlockSpace data into a litematica schema. The resulting schema data will need to be serialized
 * using the 'nbt' module before exporting
 */
export const generateLitematicaSchema = (block_space: MCBlockSpace) => {
  const blocks = block_space.reduce((blocks: litematica.BlockPosition[], columns, x) => {
    return columns.reduce((blocks, rows, z) => {
      return rows.reduce((blocks, block) => {
        blocks.push({
          id: block.id,
          properties: block.properties,
          x,
          y: block.y_offset,
          z
        });
        return blocks;
      }, blocks);
    }, blocks);
  }, []);

  return litematica.generateSchematicNBT({
    blocks,
    name: 'Map',
    author: 'Cartographer',
    description: 'MapArt schematic generated by Cartographer'
  });
};
